export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';

export const GET_TYPECATEGORIES = 'GET_TYPECATEGORIES';
export const ADD_TYPECATEGORY = 'ADD_TYPECATEGORY';
export const DELETE_TYPECATEGORY = 'DELETE_TYPECATEGORY';
export const TYPECATEGORIES_ERROR = 'TYPECATEGORIES_ERROR';

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTIONSID = 'GET_TRANSACTIONSID';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const TRANSACTIONS_ERROR = 'TRANSACTIONS_ERROR';

export const GET_BUDGETS = 'GET_BUDGETS';
export const ADD_BUDGET = 'ADD_BUDGET';
export const DELETE_BUDGET = 'DELETE_BUDGET';
export const BUDGET_ERROR = 'BUDGET_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const CHECK_LOG = 'CHECK_LOG';
export const CHECK_LOG_ERROR = 'CHECK_LOG_ERROR';

export const MODAL_TRANSC = 'MODAL_TRANSC';

export const LOADING = 'LOADING';
export const SIDEBAR = 'SIDEBAR';